name = "arv-vo"
version = 5

[device]
family = "GW5AST-138B"
part = "GW5AST-LV138FPG676AC1/I0"

[hdl]
standard = "sysv2017"

[files]
verilog = [
    "core/h14tx_timings_cursor.sv",
    "core/h14tx_timings_sync.sv",
    "top.sv",
]

[programmer]
fs = "impl/pnr/project.fs"

preset.sram = { op = "2" }
preset.spi = { op = "53" }
cst = "phy.cst"
sdc = "timing.sdc"
