name = "h14tx"
version = 5

[device]
family = "GW5AST-138B"
part = "GW5AST-LV138FPG676AC1/I0"

[hdl]
standard = "sysv2017"
top = "top_rgb"

[files]
verilog = [
  "common-cores/cores/lvds/**/*.sv",
  "core/**/*.sv",
  "top/top_rgb.sv"
]
cst = "phy.cst"
sdc = "timing.sdc"

[pnr]
place_option = 3
route_option = 1
replicate = true

[bitstream]
compress = true

[programmer]
fs = "impl/pnr/project.fs"

preset.sram = { op = "2" }
preset.spi = { op = "53" }
