name = "h14tx"
version = 5

[device]
family = "GW5AST-138B"
part = "GW5AST-LV138FPG676AC1/I0"

[hdl]
standard = "sysv2017"
include = ["include"]
top = "top_dvo"

[files]
verilog = [
]
cst = "phy.cst"
sdc = "timing.sdc"

[programmer]
fs = "impl/pnr/h14tx.fs"

preset.sram = { op = "2" }
preset.spi = { op = "53" }
